# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid
import uuid_upload_path.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=uuid_upload_path.storage.upload_to)),
                ('width', models.IntegerField(default=0, editable=False)),
                ('lateral_margins', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=1000)),
                ('background', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='design',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='showcase.Page'),
        ),
    ]
